name: Docker Image CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      SHA8: ${GITHUB_SHA::8}
    steps:
    - uses: actions/checkout@v2
    - name: Check out my other private repo
      run : |
        git clone https://.:${{ secrets.GITHUB_TOKEN }}@github.com/seyio91/gitops-flow-test
        cd gitops-flow-test && ls -R
