name: Docker Image CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      SHA8: ${GITHUB_SHA::8}
    steps:
    - uses: actions/checkout@v2
    - name: Check out my other private repo
      uses: actions/checkout@master
      with:
        repository: seyio91/gitops-flow-test
        token: ${{ secrets.GIT_TOKEN }}
    - name: Run Kustomization
      working-directory: gitops-flow-test
      run: ls -R
