name: Docker Image CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile.dev --tag seyio/react-test
    - name: Build the Docker image
      run: docker run --rm -e CI=true seyio/react-test npm test
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: seyio/react-test
        dockerfile: Dockerfile
        tag_with_sha: true
        tags: latest
