name: Docker Image CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile.dev --tag seyio/react-test
    - name: Build the Docker image
      run: docker run --rm -e CI=true seyio/react-test npm test
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: seyio/react-test
        dockerfile: Dockerfile
        tags: latest, ${{ env.GITHUB_SHA }}
    - name: Check out my other private repo
      uses: actions/checkout@master
      with:
        repository: seyio91/gitops-flow-test
    - uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.1.0"
    - name: Run Kustomization
      working-directory: ./gitops-flow-test/stage
      run: kustomize edit set image seyio/react-test:${{ env.GITHUB_SHA }}
    - name: Push New Commit
      run: git commit -am '${{ env.GITHUB_SHA }}' && git push || echo 'no changes'
